### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by thejohnd0e** [brucepro/Memoir#35]
![Screenshot - 2024-05-06 11 21 01](https://github.com/brucepro/Memoir/assets/115493464/90295e4a-1ace-496c-b7bd-253f649b5aa9)

**Comment by ZeroLogi** [comment]
I've been trying to figure this out for the last day or two with no luck. I receive the same error.

**Comment by ZeroLogi** [comment]
I seem to be getting a different error now,

`                         pip install -r extensions\Memoir\requirements.txt --upgrade

13:22:53-633010 ERROR    Failed to load the extension "Memoir".
Traceback (most recent call last):
  File "E:\Oobabooga\text-generation-webui\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Oobabooga\text-generation-webui\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Oobabooga\text-generation-webui\extensions\Memoir\script.py", line 27, in <module>
    from extensions.Memoir.commandhandler import CommandHandler
  File "E:\Oobabooga\text-generation-webui\extensions\Memoir\commandhandler.py", line 7, in <module>
    from extensions.Memoir.commands.urlhandler import UrlHandler
  File "E:\Oobabooga\text-generation-webui\extensions\Memoir\commands\urlhandler.py", line 2, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

Running on local URL:  http://127.0.0.1:7860
`

**Comment by thejohnd0e** [comment]
Unfortunately, nothing helped.


![Screenshot - 2024-05-06 23 55 08](https://github.com/brucepro/Memoir/assets/115493464/a3515189-66fe-4199-a936-4e793e45a4c7)

**Comment by ZeroLogi** [comment]
> pip install beautifulsoup4

I still got an error after this, but I ended up updating/reinstalling all extensions from the update_wizard_windows.bat and it started working just fine. Thank you for your help!

**Comment by ZeroLogi** [comment]
> Unfortunately, nothing helped.
> 
> ![Screenshot - 2024-05-06 23 55 08](https://private-user-images.githubusercontent.com/115493464/328316503-a3515189-66fe-4199-a936-4e793e45a4c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMzI5MjMsIm5iZiI6MTcxNTAzMjYyMywicGF0aCI6Ii8xMTU0OTM0NjQvMzI4MzE2NTAzLWEzNTE1MTg5LTY2ZmUtNDE5OS1hOTM2LTRlNzkzZTQ1YTRjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQyMTU3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTExZWM3MWMxYTllMTgzMDMyY2Q4ZDIxOWVkYzFmZGQ4OGU4NzU1MDg0MmJjYmM5YTJjYWMyYTE0MTNkMDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SfhKC4z05SM81Mz758iG0FJ9XmEeevO2k55tJRbiAtY)

See my reply above. I had the same error until I updated/installed everything.

**Comment by ZeroLogi** [comment]
> Hmm, could be an update doing it. From here https://pypi.org/project/python-on-whales/ looks like it was released Apr 24. I will review a clean install and see if I can figure it out. It seems that docker has been the thorn in many peoples side on install, I may have to release one that doesn't use docker and just uses the qdrant binaries. Do you have docker desktop installed?

I have docker installed. Once I ran an update for all extensions it's been working just fine, so I haven't able to pinpoint the issue. It doesn't seem to be docker related, at least on my end. Either way, your recent updates solved all of the problems I've been having for the last few days. It's been working properly as of the last few hours.

**Comment by thejohnd0e** [comment]
> > Unfortunately, nothing helped.
> > ![Screenshot - 2024-05-06 23 55 08](https://private-user-images.githubusercontent.com/115493464/328316503-a3515189-66fe-4199-a936-4e793e45a4c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMzI5MjMsIm5iZiI6MTcxNTAzMjYyMywicGF0aCI6Ii8xMTU0OTM0NjQvMzI4MzE2NTAzLWEzNTE1MTg5LTY2ZmUtNDE5OS1hOTM2LTRlNzkzZTQ1YTRjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQyMTU3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTExZWM3MWMxYTllMTgzMDMyY2Q4ZDIxOWVkYzFmZGQ4OGU4NzU1MDg0MmJjYmM5YTJjYWMyYTE0MTNkMDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SfhKC4z05SM81Mz758iG0FJ9XmEeevO2k55tJRbiAtY)
> 
> See my reply above. I had the same error until I updated/installed everything.

Of course I installed and double-checked all updates and dependencies, but it still didn't work in my case.

**Comment by thejohnd0e** [comment]
Oops.. now I see where my mistake was. Everything works well. Sorry!
